"""Only the ports required by the running local application."""
from contextlib import AbstractContextManager
from typing import Protocol
from uuid import UUID
from kdaa.domain import Workspace, SourceDocument, Run, ProvenanceEvent

class AssetStore(Protocol):
    def put(self, key: str, content: bytes) -> None: ...
    def read(self, key: str) -> bytes: ...
    def delete(self, key: str) -> None: ...
    def ready(self) -> bool: ...

class MetadataSession(Protocol):
    def add_workspace(self, item: Workspace) -> None: ...
    def get_workspace(self, id: UUID) -> Workspace | None: ...
    def list_workspaces(self) -> list[Workspace]: ...
    def add_document(self, item: SourceDocument) -> None: ...
    def get_document(self, id: UUID) -> SourceDocument | None: ...
    def list_documents(self, workspace_id: UUID) -> list[SourceDocument]: ...
    def add_run(self, item: Run) -> None: ...
    def update_run(self, item: Run) -> None: ...
    def get_run(self, id: UUID) -> Run | None: ...
    def list_runs(self, workspace_id: UUID) -> list[Run]: ...
    def unfinished_runs(self) -> list[Run]: ...
    def add_event(self, item: ProvenanceEvent) -> None: ...
    def list_events(self, workspace_id: UUID, run_id: UUID | None = None) -> list[ProvenanceEvent]: ...

class MetadataStore(Protocol):
    def transaction(self) -> AbstractContextManager[MetadataSession]: ...
    def ready(self) -> bool: ...
