import os
from alembic import context
from sqlalchemy import create_engine
from kdaa.providers.postgres import metadata

config = context.config
url = os.getenv("DATABASE_URL", config.get_main_option("sqlalchemy.url"))
schema = os.getenv("KDAA_TEST_SCHEMA")
connect_args = {}
if schema:
    # Generated by our isolated PostgreSQL test fixture, never provided by a web request.
    import re
    if not re.fullmatch(r"kdaa_test_[a-f0-9]{32}", schema):
        raise ValueError("Invalid isolated test schema name.")
    connect_args = {"options": f"-csearch_path={schema}"}
if context.is_offline_mode():
    context.configure(url=url, target_metadata=metadata, literal_binds=True, dialect_opts={"paramstyle": "named"})
    with context.begin_transaction():
        context.run_migrations()
else:
    engine = create_engine(url, connect_args=connect_args)
    with engine.connect() as connection:
        context.configure(connection=connection, target_metadata=metadata)
        with context.begin_transaction():
            context.run_migrations()
    engine.dispose()
