export type Workspace = { id: string; name: string; focal_unit: string; goal: string; created_at: string };
export type Document = { id: string; workspace_id: string; filename: string; media_type: string;
  raw_sha256: string; text_sha256: string; byte_count: number; character_count: number;
  normalization_version: string; parser_version: string; warnings: string[]; created_at: string };
export type Evidence = { id: string; workspace_id: string; run_id: string; document_id: string;
  text_sha256: string; start: number; end: number; quote: string; paragraph: number };
export type CandidateType = 'software' | 'dataset' | 'method' | 'teaching' | 'research_idea';
export type Candidate = { id: string; workspace_id: string; run_id: string; candidate_type: CandidateType;
  title: string; claim: string; evidence_ids: string[]; matched_terms: string[];
  discovery_basis: 'lexical_rules' | 'model_reading';
  status: 'provisional'; ownership: 'unresolved' };
export type SemanticAssessment = { schema_version: string; goal_relevance_explanation: string;
  possible_uses: string[]; limitations: string[]; basis: string };
export type Assessment = { candidate_id: string; traceability: string; distinct_excerpt_count: number;
  goal_relevance: string; overlapping_goal_terms: string[]; explanation: string; missing_evidence: string[];
  semantic: SemanticAssessment | null };
export type ArtifactDraft = { schema_version: string; title: string; format: string; content: string;
  grounded_evidence_ids: string[]; proposed_elements: string[]; provenance_note: string; generated_by: string };
export type Amplification = { candidate_id: string; evidence_ids: string[]; proposed_artifact: string;
  next_action: string; rationale: string; verification_gate: string; baseline: string; status: string;
  draft: ArtifactDraft | null };
export type EvidenceRejection = { schema_version: string; stage: string; reason: string;
  document_id: string | null; candidate_title: string; quote_sha256: string; quote_preview: string; detail: string };
export type LLMInteraction = { stage: string; prompt_version: string; record_key: string;
  stop_reason: string; usage: Record<string, number>; latency_ms: number };
export type ProviderRecord = { provider: string; model: string; region: string; simulated: boolean;
  prompt_versions: Record<string, string>; usage: Record<string, number>; calls: number;
  interactions: LLMInteraction[] };
export type Bundle = { hypotheses: Candidate[]; evidence: Evidence[]; assessments: Assessment[];
  amplifications: Amplification[]; input_document_count: number; unique_text_count: number;
  duplicate_text_count: number; unique_excerpt_count: number; notes: string[]; disclaimer: string;
  provider: ProviderRecord | null; rejections: EvidenceRejection[] };
export type RunStatus = 'pending' | 'running' | 'succeeded' | 'failed' | 'interrupted';
export type RunSummary = { id: string; workspace_id: string; status: RunStatus; created_at: string;
  updated_at: string; engine_version: string; candidate_count: number | null; error: Record<string, string> | null };
export type Run = Omit<RunSummary, 'candidate_count'> & { inputs: { document_id: string; filename: string;
  raw_sha256: string; text_sha256: string }[]; config: Record<string, unknown>; config_sha256: string;
  result: Bundle | null; schema_version: string };
export type Event = { id: string; workspace_id: string; run_id: string | null; actor: string; action: string;
  source_ids: string[]; evidence_ids: string[]; output_ids: string[]; timestamp: string;
  details: Record<string, unknown>; engine_version: string; config_sha256: string | null };
export type EvidenceView = { evidence: Evidence; filename: string; before: string; quote: string;
  after: string; locator_unit: string; verified: boolean };
export type ContentView = { document_id: string; filename: string; text: string; text_sha256: string;
  normalization_version: string };
export type RunMode = 'reference' | 'live';
export type LLMInfo = { enabled: boolean; provider: string; model: string; region: string;
  max_input_chars: number; max_output_tokens: number; max_model_calls: number;
  timeout_seconds: number; total_attempts: number };
export type SystemInfo = { mode: RunMode; modes: RunMode[]; engine: string; live_llm: boolean;
  local_only: boolean; disclaimer: string; version: string; llm: LLMInfo };
