import html
import re
from kdaa.domain import DISCLAIMER, Run, ProvenanceEvent

def safe(value: str) -> str:
    return html.escape(value).replace("[", r"\[").replace("]", r"\]").replace("*", r"\*")

def fenced(value: str) -> str:
    longest = max((len(x) for x in re.findall(r"`+", value)), default=0)
    fence = "`" * max(3, longest + 1)
    return f"{fence}text\n{value}\n{fence}"

def markdown_report(run: Run, events: list[ProvenanceEvent]) -> str:
    # Use the bundle's own disclaimer: a live result must not be exported under the reference text.
    disclaimer = run.result.disclaimer if run.result else DISCLAIMER
    lines = ["# KDAA run report", "", disclaimer, "", f"Run: `{run.id}`", f"Status: **{run.status.value}**",
             f"Mode: **{run.config.get('mode', 'reference')}**", f"Engine: `{run.engine_version}`",
             f"Configuration SHA-256: `{run.config_sha256}`",
             f"Created: {run.created_at.isoformat()}", "", "## Input snapshot", ""]
    for source in run.inputs:
        lines.extend([f"- {safe(source.filename)} — `{source.document_id}`", f"  Normalized SHA-256: `{source.text_sha256}`"])
    if not run.result:
        lines.extend(["", "No completed result bundle.", safe((run.error or {}).get("message", "Run is not complete."))])
    else:
        bundle = run.result
        if bundle.provider:
            provider = bundle.provider
            lines.extend(["", "## Model", "",
                          f"Provider: `{provider.provider}` · model: `{provider.model}`"
                          + (f" · region: `{provider.region}`" if provider.region else ""),
                          f"Simulated: {provider.simulated}. Model calls: {provider.calls}.",
                          f"Prompt versions: {', '.join(f'{k}={v}' for k, v in sorted(provider.prompt_versions.items()))}.",
                          f"Token usage: {', '.join(f'{k}={v}' for k, v in sorted(provider.usage.items())) or 'not reported'}."])
        evidence = {e.id: e for e in bundle.evidence}
        assessments = {a.candidate_id: a for a in bundle.assessments}
        actions = {a.candidate_id: a for a in bundle.amplifications}
        for candidate in bundle.hypotheses:
            assessment, action = assessments[candidate.id], actions[candidate.id]
            lines.extend(["", f"## {safe(candidate.title)}", "", "Status: provisional; ownership: unresolved.",
                "", safe(candidate.claim), "", "### Assessment", "", safe(assessment.explanation),
                f"Distinct excerpts: {assessment.distinct_excerpt_count} (not independent corroboration)."])
            if assessment.semantic:
                semantic = assessment.semantic
                lines.extend(["", "Goal relevance (a model reading, not a score): "
                              + safe(semantic.goal_relevance_explanation)])
                if semantic.possible_uses:
                    lines.extend(["", "Possible uses:", *[f"- {safe(x)}" for x in semantic.possible_uses]])
                if semantic.limitations:
                    lines.extend(["", "Limitations:", *[f"- {safe(x)}" for x in semantic.limitations]])
            else:
                lines.append(f"Goal relevance: {assessment.goal_relevance}; overlapping terms: "
                             f"{', '.join(assessment.overlapping_goal_terms) or 'none'}.")
            lines.extend(["", "Still to verify:"])
            lines.extend(f"- {safe(x)}" for x in assessment.missing_evidence)
            lines.extend(["", "### Amplification proposal", "", f"**{safe(action.proposed_artifact)}**", "",
                          safe(action.next_action), "", f"Verification gate: {safe(action.verification_gate)}", "", safe(action.baseline)])
            if action.draft:
                draft = action.draft
                lines.extend(["", f"### Generated draft: {safe(draft.title)}", "", draft.provenance_note, "",
                              f"Generated by: `{safe(draft.generated_by)}`.", "",
                              "The draft is reproduced verbatim below. It is proposed content, not source-supported fact.",
                              "", fenced(draft.content), ""])
                if draft.proposed_elements:
                    lines.extend(["Proposed, not supported by the quoted evidence:",
                                  *[f"- {safe(x)}" for x in draft.proposed_elements], ""])
                if draft.grounded_evidence_ids:
                    lines.append("Source-supported evidence cited by this draft: "
                                 + ", ".join(f"`{i}`" for i in draft.grounded_evidence_ids))
            lines.extend(["", "### Evidence", ""])
            for id in candidate.evidence_ids:
                e = evidence[id]
                lines.extend([f"Evidence `{e.id}` · source `{e.document_id}` · normalized offsets [{e.start}, {e.end}).",
                              "", fenced(e.quote), ""])
        lines.extend(["", "## Limitations", "", *[f"- {safe(x)}" for x in bundle.notes]])
        if bundle.rejections:
            lines.extend(["", "## Rejected model quotations", "",
                          "Produced by the model and refused by evidence validation. They are not evidence.", ""])
            for rejection in bundle.rejections:
                lines.append(f"- `{rejection.reason}` · {safe(rejection.candidate_title) or 'candidate'} · "
                             f"{safe(rejection.detail)}")
    lines.extend(["", "## Provenance", ""])
    lines.extend(f"- {e.timestamp.isoformat()} · `{e.action}` · `{e.id}`" for e in events)
    return "\n".join(lines) + "\n"
