"""Real browser checks for uploaded formats and edge cases, against an already running app.

Complements scripts/browser_smoke.py (demo workflow). Covers the upload matrix the local
acceptance requires: text-based PDF, DOCX, an irrelevant TXT with no candidates, a duplicate
source that adds no independent support, malformed files that must report a readable error
without killing the service, and the Markdown export.

    python scripts/browser_uploads.py --base http://127.0.0.1:5183 --fixtures <dir>

Fixtures are generated by the caller (see docs/TESTING.md). Never deletes app data.
"""
import argparse
import json
import os
import tempfile
import urllib.request
from pathlib import Path
from uuid import uuid4
from playwright.sync_api import sync_playwright, expect


def new_workspace(page, name, goal):
    page.get_by_role("button", name="New workspace", exact=True).click()
    page.get_by_label("Workspace name", exact=True).fill(name)
    page.get_by_label("What could this material help you do?").fill(goal)
    page.get_by_role("button", name="Create workspace", exact=True).click()


def wait_idle(page):
    """The hidden file input skips actionability, so wait for the workspace view to be interactive."""
    expect(page.get_by_role("button", name="Load demo", exact=True)).to_be_enabled(timeout=30000)
    expect(page.locator(".progress")).to_have_count(0, timeout=60000)


def upload(page, paths):
    page.get_by_role("tab", name="Sources").click()
    wait_idle(page)
    page.locator("input[type=file]").set_input_files([str(p) for p in paths])
    wait_idle(page)


def clear_selection(page):
    head = page.get_by_role("button", name="Clear selection", exact=True)
    if head.count():
        head.click()


def select_only(page, filenames):
    """Filenames may repeat; a duplicate import shows one row per import."""
    clear_selection(page)
    for filename in sorted(set(filenames)):
        boxes = page.get_by_label(f"Select {filename}", exact=True)
        for index in range(filenames.count(filename)):
            boxes.nth(index).check()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--base", default="http://127.0.0.1:5183")
    parser.add_argument("--api", default="http://127.0.0.1:8183")
    parser.add_argument("--fixtures", type=Path, required=True)
    parser.add_argument("--screenshots", type=Path)
    args = parser.parse_args()
    fx = args.fixtures
    errors = []
    results = {}
    with sync_playwright() as p, tempfile.TemporaryDirectory() as temporary:
        browser = p.chromium.launch(headless=True, executable_path=os.getenv("CHROMIUM_EXECUTABLE") or None)
        page = browser.new_page(viewport={"width": 1440, "height": 1050})
        page.on("pageerror", lambda error: errors.append(str(error)))
        page.goto(args.base)
        new_workspace(page, f"Upload acceptance {uuid4().hex[:6]}",
                      "Reuse a software package and a written protocol as teaching material.")

        # 1. Real text-based PDF and DOCX are extracted and stored.
        wait_idle(page)
        upload(page, [fx / "upload-software.pdf", fx / "upload-method.docx"])
        expect(page.get_by_role("button", name="upload-software.pdf", exact=True)).to_be_visible(timeout=30000)
        expect(page.get_by_role("button", name="upload-method.docx", exact=True)).to_be_visible(timeout=30000)
        results["pdf_docx_imported"] = True

        # 2. A run over the PDF and DOCX produces candidates from the uploaded text.
        select_only(page, ["upload-software.pdf", "upload-method.docx"])
        page.get_by_role("button", name="Run KDAA", exact=True).click()
        expect(page.get_by_role("heading", name="Candidate knowledge assets", exact=True)).to_be_visible(timeout=60000)
        results["uploaded_candidates"] = page.locator(".candidate-card").count()
        assert results["uploaded_candidates"] > 0, "Uploaded PDF/DOCX produced no candidates"
        page.get_by_role("button", name="Inspect evidence 1 for").first.click()
        dialog = page.get_by_role("dialog", name="Evidence inspector")
        expect(dialog.get_by_text("Exact quote verified", exact=True)).to_be_visible()
        page.get_by_role("button", name="Close dialog", exact=True).click()
        if args.screenshots:
            args.screenshots.mkdir(parents=True, exist_ok=True)
            page.screenshot(path=str(args.screenshots / "uploads-discovery.png"), full_page=True)

        # 3. Markdown export downloads and contains the run.
        with page.expect_download() as event:
            page.get_by_role("button", name="Export Markdown", exact=True).click()
        target = Path(temporary) / "run.md"
        event.value.save_as(target)
        markdown = target.read_text(encoding="utf-8")
        assert markdown.lstrip().startswith("#"), "Markdown export is not a Markdown document"
        assert "upload-software.pdf" in markdown, "Markdown export does not cite the uploaded source"
        results["markdown_export_bytes"] = len(markdown)
        with page.expect_download() as event:
            page.get_by_role("button", name="Export JSON", exact=True).click()
        target = Path(temporary) / "run.json"
        event.value.save_as(target)
        exported = json.loads(target.read_text(encoding="utf-8"))
        results["json_export_sources"] = len(exported["sources"])

        # 4. A duplicate import is retained but adds no independent support.
        upload(page, [fx / "upload-software.pdf"])
        expect(page.get_by_text("Duplicate text", exact=True).first).to_be_visible(timeout=30000)
        select_only(page, ["upload-software.pdf", "upload-software.pdf"])
        page.get_by_role("button", name="Run KDAA", exact=True).click()
        expect(page.get_by_role("heading", name="Candidate knowledge assets", exact=True)).to_be_visible(timeout=60000)
        note = page.locator(".snapshot-note").inner_text()
        assert "1 unique text" in note and "duplicate" in note.lower(), f"Duplicate accounting not shown: {note}"
        duplicate_candidates = page.locator(".candidate-card").count()
        results["duplicate_note"] = " ".join(note.split())
        results["duplicate_run_candidates"] = duplicate_candidates

        # 5. An irrelevant source yields no candidates, stated without claiming the source is worthless.
        upload(page, [fx / "irrelevant.txt"])
        expect(page.get_by_role("button", name="irrelevant.txt", exact=True)).to_be_visible(timeout=30000)
        select_only(page, ["irrelevant.txt"])
        page.get_by_role("button", name="Run KDAA", exact=True).click()
        expect(page.get_by_text("No supported candidates under these rules", exact=True)).to_be_visible(timeout=60000)
        assert page.locator(".candidate-card").count() == 0
        results["irrelevant_no_candidates"] = True

        # 6. Malformed files report a readable error; the service stays up.
        malformed_messages = []
        for name in ["malformed.pdf", "malformed.docx"]:
            upload(page, [fx / name])
            alert = page.locator(".alert.error[role=alert]")
            expect(alert).to_be_visible(timeout=30000)
            message = alert.inner_text().strip()
            assert len(message) > 10 and "Traceback" not in message, f"Unreadable error for {name}: {message}"
            malformed_messages.append({name: " ".join(message.split())})
            expect(page.get_by_role("button", name=name, exact=True)).to_have_count(0)
            page.get_by_role("button", name="Dismiss error", exact=True).click()
        results["malformed_errors"] = malformed_messages
        with urllib.request.urlopen(args.api + "/ready", timeout=10) as response:
            assert json.loads(response.read())["ready"] is True
        results["service_alive_after_malformed"] = True

        # 7. Provenance and a reload still show the stored sources.
        page.reload()
        expect(page.get_by_role("button", name="upload-software.pdf", exact=True).first).to_be_visible(timeout=30000)
        page.get_by_role("tab", name="Provenance", exact=True).click()
        expect(page.get_by_text("run · succeeded", exact=True).first).to_be_visible()
        results["reload_and_provenance"] = True

        assert not errors, errors
        browser.close()
    print(json.dumps({"passed": True, **results}, indent=2))


if __name__ == "__main__":
    main()
