"""Produce a schema-accurate live run bundle for the live-mode UI rendering check.

The bundle is generated by the real LiveEngine driven by the fixture provider, so it matches the
shape a genuine Bedrock run would store. It is UI test input only: it is never served by the
application and is not evidence that a real model call works.

    docker compose run --rm --no-deps --user root \
        -v "$PWD/scripts/make_live_ui_fixture.py":/tmp/make_live_ui_fixture.py \
        -v "$PWD/.fixtures":/out kdaa-tests python /tmp/make_live_ui_fixture.py --out /out/live-run.json
"""
import argparse
import json
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, "/app/src")
sys.path.insert(0, "/app/services/api")

from kdaa.core.llm_engine import LiveEngine
from kdaa.core.service import KDAAService
from kdaa.providers.llm import StubLLMProvider
from kdaa.providers.local import LocalAssetStore
sys.path.insert(0, "/app")
from tests.support import MemoryStore

SOURCE = (b"Copperfin field toolkit\n\n"
          b"The Copperfin utility cleans messy field notes before analysis and ships with a small "
          b"command line entry point.\n\n"
          b"A short protocol describes how two reviewers reconcile disagreements in the notes.\n")
QUOTE = ("The Copperfin utility cleans messy field notes before analysis and ships with a small "
         "command line entry point.")

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", type=Path, required=True)
    out = parser.parse_args().out
    with tempfile.TemporaryDirectory() as temporary:
        core = None
        provider = StubLLMProvider({})
        engine = LiveEngine(provider)
        core = KDAAService(MemoryStore(), LocalAssetStore(Path(temporary)), engines={"live": engine})
        workspace = core.create_workspace("Live UI fixture", "Fictional group",
                                          "Reuse tooling for field notes")
        document = core.import_document(workspace.id, "copperfin.txt", SOURCE)
        provider._responses = {
            "discovery": json.dumps({"candidates": [
                {"type": "software", "title": "Copperfin note-cleaning utility",
                 "claim": "A reusable command line cleaner may exist. Ownership and licence are unverified.",
                 "quotes": [{"document_id": str(document.id), "quote": QUOTE}]},
                {"type": "method", "title": "Unfounded reviewer protocol",
                 "claim": "This candidate cites text that is not in the source.",
                 "quotes": [{"document_id": str(document.id),
                             "quote": "Two reviewers achieved 98% agreement in a validated trial."}]}]}),
            "assessment": lambda request: json.dumps({"assessments": [
                {"candidate_id": cid,
                 "goal_relevance_explanation": "Directly relevant: the goal is reusing tooling for field notes, and the source describes such a tool.",
                 "possible_uses": ["Run it over an example set of notes before analysis",
                                   "Use it as a worked example in an onboarding session"],
                 "limitations": ["The source does not show the code, tests or licence",
                                 "Only one passage mentions the tool"],
                 "missing_evidence": ["Repository location and licence", "Whether it still runs"]}
                for cid in __import__("re").findall(r"candidate_id: ([0-9a-f-]{36})", request.user)]}),
            "amplification": json.dumps({
                "title": "Copperfin quick-start README",
                "proposed_artifact": "README draft",
                "content": ("# Copperfin\n\n## What it does\nCleans messy field notes before analysis.\n\n"
                            "## Getting started\n1. Copy your notes to a working directory.\n"
                            "2. Run the command line entry point against that copy.\n"
                            "3. Compare a sample of cleaned records against the originals.\n\n"
                            "## Before you rely on it\nConfirm the licence and the current owner."),
                "proposed_elements": ["The three getting-started steps are proposed; the source does not document any commands.",
                                      "The heading structure is proposed."],
                "grounded_evidence_ids": [],
                "next_action": "Locate the repository and confirm the entry point name.",
                "verification_gate": "Confirm ownership and licence before sharing this draft."})}
        run = core.start_run(workspace.id, mode="live")
        if run.status.value != "succeeded":
            raise SystemExit(f"fixture run failed: {run.error}")
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(run.model_dump_json(indent=2), encoding="utf-8")
        print(f"{out} candidates={len(run.result.hypotheses)} rejections={len(run.result.rejections)} "
              f"drafts={sum(1 for a in run.result.amplifications if a.draft)}")

if __name__ == "__main__":
    main()
